=== runtipi/runtipi-appstore/apps/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "available": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean"
    },
    "exposable": {
      "type": "boolean"
    },
    "no_gui": {
      "type": "boolean"
    },
    "port": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "https": {
      "type": "boolean"
    },
    "uid": {
      "type": "integer"
    },
    "gid": {
      "type": "integer"
    },
    "force_expose": {
      "type": "boolean"
    },
    "generate_vapid_keys": {
      "type": "boolean"
    },
    "requirements": {
      "type": "object",
      "properties": {
        "ports": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        }
      }
    },
    "supported_architectures": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-_]+$"
    },
    "tipi_version": {
      "type": "integer"
    },
    "version": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "short_desc": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "source": {
      "type": "string",
      "format": "uri"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "url_suffix": {
      "type": "string",
      "pattern": "^/[a-z0-9-_/]+$"
    },
    "form_fields": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "max": {
              "type": "integer"
            },
            "min": {
              "type": "integer"
            },
            "required": {
              "type": "boolean"
            },
            "env_variable": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "label",
            "env_variable"
          ]
        }
      ]
    },
    "dynamic_config": {
      "type": "boolean"
    },
    "created_at": {
      "type": "number"
    },
    "updated_at": {
      "type": "number"
    }
  },
  "required": [
    "name",
    "available",
    "port",
    "id",
    "tipi_version",
    "version",
    "categories",
    "description",
    "short_desc",
    "author",
    "source",
    "form_fields"
  ]
}

=== runtipi/runtipi-appstore/apps/moneroblock/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "Moneroblock",
  "available": true,
  "exposable": true,
  "dynamic_config": true,
  "port": 31312,
  "id": "moneroblock",
  "tipi_version": 4,
  "version": "0.1.2",
  "categories": ["utilities"],
  "description": "MoneroBlock is a trustless block explorer for the Monero payment network.",
  "short_desc": "Decentralized and trustless Monero block explorer",
  "author": "duggavo",
  "source": "https://github.com/duggavo/MoneroBlock",
  "form_fields": [
    {
      "type": "text",
      "label": "Monero Daemon",
      "hint": "Address in format node.host.name:port, i.e. node.sethforprivacy.com:18089",
      "max": 100,
      "min": 10,
      "required": false,
      "env_variable": "DAEMON_ADDRESS"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1738177511711
}

=== runtipi/runtipi-appstore/apps/photoprism/config.json
{
  "$schema": "../schema.json",
  "name": "PhotoPrism",
  "port": 8110,
  "available": true,
  "exposable": true,
  "id": "photoprism",
  "tipi_version": 5,
  "version": "240420",
  "categories": ["photography"],
  "description": "PhotoPrismÂ® is an AI-Powered Photos App for the Decentralized Web. It makes use of the latest technologies to tag and find pictures automatically without getting in your way. You can run it at home, on a private server, or in the cloud. Default username: admin",
  "short_desc": "AI-Powered Photos App for the Decentralized Web. We are on a mission to protect your freedom and privacy.",
  "author": "PhotoPrism",
  "source": "https://github.com/photoprism/photoprism",
  "form_fields": [
    {
      "type": "password",
      "label": "Photoprism admin password",
      "max": 50,
      "min": 8,
      "required": true,
      "env_variable": "PHOTOPRISM_ADMIN_PASSWORD"
    },
    {
      "type": "random",
      "label": "Photoprism DB password",
      "env_variable": "DB_PASSWORD"
    },
    {
      "type": "random",
      "label": "Photoprism root DB password",
      "env_variable": "DB_ROOT_PASSWORD"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1723566284000
}

=== runtipi/runtipi-appstore/apps/revolt/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "Revolt Chat",
  "port": 8272,
  "available": true,
  "exposable": true,
  "dynamic_config": true,
  "force_expose": true,
  "generate_vapid_keys": true,
  "id": "revolt",
  "tipi_version": 14,
  "version": "20230810-3",
  "categories": ["media"],
  "description": "Open source user-first chat platform.",
  "short_desc": "Open source user-first chat platform.",
  "author": "RevoltChat",
  "source": "https://github.com/revoltchat",
  "form_fields": [
    {
      "type": "random",
      "label": "Revlot Minio Root Password",
      "min": 32,
      "env_variable": "REVOLT_MINIO_ROOT_PASSWORD"
    },
    {
      "type": "random",
      "label": "Revlot Minio Root Password",
      "min": 32,
      "env_variable": "REVOLT_MINIO_ROOT_PASSWORD"
    },
    {
      "type": "random",
      "label": "Revlot AWS Access Key",
      "min": 16,
      "max": 16,
      "env_variable": "REVOLT_AWS_ACCESS_KEY_ID"
    },
    {
      "type": "random",
      "label": "Revlot AWS Secret Access Key",
      "min": 32,
      "max": 32,
      "env_variable": "REVOLT_AWS_SECRET_ACCESS_KEY"
    },
    {
      "type": "text",
      "label": "SMTP Host",
      "hint": "Your SMTP Server",
      "placeholder": "smtp.example.com",
      "required": true,
      "env_variable": "REVOLT_SMTP_HOST"
    },
    {
      "type": "text",
      "label": "SMTP Username",
      "hint": "Your SMTP Server User/Username",
      "placeholder": "noreply@example.com",
      "required": true,
      "env_variable": "REVOLT_SMTP_USERNAME"
    },
    {
      "type": "text",
      "label": "SMTP Password",
      "hint": "Your SMTP Server Password",
      "required": true,
      "env_variable": "REVOLT_SMTP_PASSWORD"
    },
    {
      "type": "text",
      "label": "SMTP From Address",
      "hint": "Make sure the Format is like Revolt <noreply@example.com>",
      "placeholder": "Revolt <noreply@example.com>",
      "required": true,
      "env_variable": "REVOLT_SMTP_FROM"
    },
    {
      "label": "Revolt Invite Only",
      "type": "text",
      "hint": "Choose whether you want Open Signups or have the Platform Invite Only",
      "required": true,
      "options": [
        {
          "label": "Open Signups",
          "value": "0"
        },
        {
          "label": "Invite Only",
          "value": "1"
        }
      ],
      "env_variable": "REVOLT_INVITE_ONLY"
    }
  ],
  "supported_architectures": ["amd64"],
  "created_at": 1691943801422,
  "updated_at": 1738177580091
}

=== runtipi/runtipi-appstore/apps/smallweb/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "Smallweb",
  "id": "smallweb",
  "available": true,
  "short_desc": "Your internet folder",
  "author": "pomdtr",
  "port": 7777,
  "categories": ["development"],
  "description": "A self-hostable personal cloud inspired by serverless platforms and cgi-bin",
  "tipi_version": 18,
  "version": "0.23.1",
  "source": "https://github.com/pomdtr/smallweb",
  "website": "https://smallweb.run",
  "exposable": true,
  "dynamic_config": true,
  "supported_architectures": ["arm64", "amd64"],
  "form_fields": [
    {
      "env_variable": "SMALLWEB_DOMAIN",
      "placeholder": "smallweb.mydomain.com",
      "hint": "Smallweb requires a main domain to function properly, this can be the domain you set in the expose field or the .local one",
      "label": "Smallweb Domain",
      "type": "text",
      "required": true
    }
  ],
  "created_at": 1724134338800,
  "updated_at": 1740331804534
}

=== runtipi/runtipi-appstore/apps/homey-self-hosted-server/config.json
{
  "name": "Homey Self-Hosted Server",
  "id": "homey-self-hosted-server",
  "available": true,
  "short_desc": "Run homey self-hosted server on your own host.",
  "author": "Athom B.V.",
  "port": 4859,
  "categories": [
    "automation"
  ],
  "description": "Self-hosted Homey server for local smart home automation.",
  "tipi_version": 2,
  "version": "latest",
  "source": "https://support.homey.app/hc/en-us/articles/24010537261980-How-to-install-Homey-Self-Hosted-Server-with-Docker-on-Linux",
  "exposable": false,
  "supported_architectures": [
    "arm64",
    "amd64"
  ],
  "created_at": 1778495895001,
  "updated_at": 1778495895001,
  "dynamic_config": true,
  "form_fields": []
}

=== runtipi/runtipi-appstore/apps/duckdns/config.json
{
  "name": "Duck DNS",
  "available": true,
  "port": 8026,
  "exposable": false,
  "id": "duckdns",
  "description": "Duck DNS is a free service which will point a DNS (sub domains of duckdns.org) to an IP of your choice",
  "tipi_version": 1,
  "no_gui": true,
  "version": "b14c520a-ls8",
  "categories": ["network"],
  "short_desc": "Duck DNS is a free Dynamic DNS service",
  "author": "linuxserver.io",
  "source": "https://github.com/linuxserver/docker-duckdns",
  "website": "https://docs.linuxserver.io/images/docker-duckdns/",
  "supported_architectures": ["arm64", "amd64"],
  "form_fields": [
    {
      "type": "text",
      "label": "Subdomains (comma separated). E.g. `mydomain1,mydomain2`.",
      "max": 1024,
      "min": 3,
      "required": true,
      "env_variable": "DUCKDNS_SUBDOMAINS"
    },
    {
      "type": "password",
      "label": "DuckDNS Token",
      "max": 128,
      "min": 3,
      "required": true,
      "env_variable": "DUCKDNS_TOKEN"
    },
    {
      "type": "text",
      "label": "Update IP (blank, ipv4, ipv6 or both). Setting this value uses external Cloudflare whoami service. Omitting the field uses DuckDNS for detection and only supports IPv4.",
      "required": false,
      "env_variable": "DUCKDNS_UPDATE_IP"
    },
    {
      "type": "boolean",
      "label": "Enable logging",
      "required": false,
      "env_variable": "DUCKDNS_ENABLE_LOG_FILE"
    }
  ],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}

=== runtipi/runtipi-appstore/apps/pairdrop/config.json
{
  "$schema": "../schema.json",
  "name": "PairDrop",
  "port": 8182,
  "available": true,
  "exposable": true,
  "dynamic_config": true,
  "id": "pairdrop",
  "tipi_version": 29,
  "version": "1.10.10",
  "categories": ["media", "data", "utilities"],
  "description": "Local file sharing in your browser. Inspired by Apple's AirDrop",
  "short_desc": "Local file sharing in your browser. Inspired by Apple's AirDrop",
  "author": "schlagmichdoch",
  "source": "https://github.com/schlagmichdoch/PairDrop",
  "website": "https://pairdrop.net/",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1729872813705
}

=== runtipi/runtipi-appstore/apps/seedsync/config.json
{
  "$schema": "../schema.json",
  "name": "SeedSync",
  "available": true,
  "port": 8800,
  "exposable": true,
  "id": "seedsync",
  "description": "SeedSync is a tool to sync the files on a remote Linux server (like your seedbox, for example). It uses LFTP to transfer files fast!",
  "tipi_version": 1,
  "version": "0.8.6",
  "categories": ["utilities"],
  "short_desc": "SeedSync is a tool to sync the files on a remote Linux server.",
  "author": "Inderpreet Singh",
  "source": "https://github.com/ipsingh06/seedsync",
  "website": "https://ipsingh06.github.io/seedsync/",
  "supported_architectures": ["amd64", "arm64"],
  "form_fields": [
    {
      "type": "number",
      "label": "UID",
      "hint": "Ensure any volume directories on the host are owned by the same user you specify",
      "placeholder": "1000",
      "env_variable": "SEEDSYNC_PUID"
    },
    {
      "type": "number",
      "label": "GUID",
      "hint": "Ensure any volume directories on the host are owned by the same group you specify",
      "placeholder": "1000",
      "env_variable": "SEEDSYNC_PGID"
    }
  ],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}
