=== runtipi/runtipi-appstore/apps/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "available": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean"
    },
    "exposable": {
      "type": "boolean"
    },
    "no_gui": {
      "type": "boolean"
    },
    "port": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "https": {
      "type": "boolean"
    },
    "uid": {
      "type": "integer"
    },
    "gid": {
      "type": "integer"
    },
    "force_expose": {
      "type": "boolean"
    },
    "generate_vapid_keys": {
      "type": "boolean"
    },
    "requirements": {
      "type": "object",
      "properties": {
        "ports": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        }
      }
    },
    "supported_architectures": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-_]+$"
    },
    "tipi_version": {
      "type": "integer"
    },
    "version": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "short_desc": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "source": {
      "type": "string",
      "format": "uri"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "url_suffix": {
      "type": "string",
      "pattern": "^/[a-z0-9-_/]+$"
    },
    "form_fields": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "max": {
              "type": "integer"
            },
            "min": {
              "type": "integer"
            },
            "required": {
              "type": "boolean"
            },
            "env_variable": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "label",
            "env_variable"
          ]
        }
      ]
    },
    "dynamic_config": {
      "type": "boolean"
    },
    "created_at": {
      "type": "number"
    },
    "updated_at": {
      "type": "number"
    }
  },
  "required": [
    "name",
    "available",
    "port",
    "id",
    "tipi_version",
    "version",
    "categories",
    "description",
    "short_desc",
    "author",
    "source",
    "form_fields"
  ]
}

=== runtipi/runtipi-appstore/apps/librephotos/config.json
{
  "$schema": "../schema.json",
  "name": "LibrePhotos",
  "port": 8132,
  "available": true,
  "exposable": true,
  "id": "librephotos",
  "tipi_version": 14,
  "version": "2023w48",
  "categories": ["photography"],
  "description": "Complete photo management service",
  "short_desc": "Complete photo management service",
  "author": "Niaz Faridani-Rad",
  "source": "https://github.com/LibrePhotos/librephotos",
  "form_fields": [
    {
      "type": "email",
      "label": "LibrePhotos admin email",
      "required": true,
      "env_variable": "LIBREPHOTOS_EMAIL"
    },
    {
      "type": "text",
      "label": "LibrePhotos admin username",
      "max": 50,
      "min": 3,
      "required": true,
      "env_variable": "LIBREPHOTOS_USERNAME"
    },
    {
      "type": "password",
      "label": "LibrePhotos admin password",
      "max": 50,
      "min": 8,
      "required": true,
      "env_variable": "LIBREPHOTOS_PASSWORD"
    },
    {
      "type": "random",
      "label": "DB password",
      "env_variable": "LIBREPHOTOS_DB_PASSWORD"
    },
    {
      "type": "random",
      "label": "Secret key",
      "env_variable": "LIBREPHOTOS_SECRET_KEY"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}

=== runtipi/runtipi-appstore/apps/nextgba/config.json
{
  "name": "NextGBA",
  "available": true,
  "port": 8435,
  "exposable": true,
  "dynamic_config": true,
  "id": "nextgba",
  "description": "All of your favorite gameboy games in your browser",
  "tipi_version": 6,
  "version": "0.1.0",
  "categories": ["gaming"],
  "short_desc": "Gameboy in your browser",
  "author": "meienberger",
  "source": "https://github.com/meienberger/nextgba",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1729872793139
}

=== runtipi/runtipi-appstore/apps/affine/config.json
{
  "name": "AFFiNE",
  "id": "affine",
  "available": true,
  "short_desc": "AFFiNE is a workspace with fully merged docs, whiteboards and databases.",
  "author": "https://github.com/toeverything",
  "port": 3010,
  "categories": [
    "utilities"
  ],
  "description": "AFFiNE is a workspace with fully merged docs, whiteboards and databases. A privacy-focused, local-first, open-source, and ready-to-use alternative for Notion & Miro. Docs, canvas and tables are hyper-merged with AFFiNE - just like the word affine",
  "tipi_version": 2,
  "version": "stable",
  "source": "https://github.com/toeverything/affine",
  "website": "https://affine.pro",
  "exposable": true,
  "form_fields": [
    {
      "env_variable": "AFFINE_ADMIN_EMAIL",
      "label": "Admin Email",
      "pattern_error": "Invalid email",
      "regex": "^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,}$",
      "required": true,
      "type": "text"
    },
    {
      "env_variable": "AFFINE_ADMIN_PASSWORD",
      "label": "Admin Password",
      "pattern_error": "Invalid password: Must have 1 lowercase, 1 uppercase, 1 special character, 1 digit and no $.",
      "regex": "^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s$]){8,128}$",
      "required": true,
      "type": "password",
      "min": 8,
      "max": 128
    },
    {
      "env_variable": "AFFINE_TELEMETRY_ENABLE",
      "label": "Enable affine telemetry?",
      "required": false,
      "type": "boolean"
    },
    {
      "env_variable": "AFFINE_POSTGRES_PASSWORD",
      "label": "Affine postgres password",
      "type": "random",
      "min": 32
    }
  ],
  "supported_architectures": [
    "arm64",
    "amd64"
  ],
  "created_at": 1691943801422,
  "updated_at": 1723566284000
}

=== runtipi/runtipi-appstore/apps/homepage/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "Homepage",
  "available": true,
  "exposable": true,
  "port": 8756,
  "tipi_version": 37,
  "version": "v1.4.0",
  "id": "homepage",
  "categories": ["utilities"],
  "description": "A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations for over 100 services and translations into multiple languages.",
  "short_desc": "A highly customizable homepage",
  "author": "gethomepage",
  "source": "https://github.com/gethomepage/homepage",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"],
  "dynamic_config": true,
  "created_at": 1691943801422,
  "updated_at": 1753073876767
}

=== runtipi/runtipi-appstore/apps/dailytxt/config.json
{
  "$schema": "../schema.json",
  "name": "DailyTxT",
  "port": 8156,
  "available": true,
  "exposable": true,
  "id": "dailytxt",
  "tipi_version": 7,
  "version": "1.0.15",
  "categories": ["utilities"],
  "description": "DailyTxT is an encrypted Diary Web-App to write down your stories of the day and to find them again easily.",
  "short_desc": "Encrypted Diary Web-App",
  "author": "PhiTux",
  "source": "https://github.com/PhiTux/DailyTxT",
  "form_fields": [
    {
      "type": "random",
      "label": "DailyTXT Secret Key",
      "min": 32,
      "env_variable": "DAILYTXT_SECRET_KEY"
    },
    {
      "type": "boolean",
      "label": "Allow User Registrastion",
      "hint": "Set it to true intially to create the first user.",
      "placeholder": "true",
      "default": true,
      "env_variable": "DAILYTXT_ALLOW_REGISTRATION"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1723566284000
}

=== runtipi/runtipi-appstore/apps/lobe-chat/config.json
{
  "name": "Lobe Chat",
  "available": true,
  "port": 3210,
  "exposable": true,
  "id": "lobe-chat",
  "description": "LobeChat is an open-source, high-performance chatbot framework that supports speech synthesis, multimodal, and extensible (Function Call) plugin system.",
  "tipi_version": 222,
  "version": "1.9.1",
  "categories": ["ai"],
  "short_desc": "LLM chatbot framework",
  "author": "https://github.com/lobehub",
  "source": "https://github.com/lobehub/lobe-chat",
  "website": "https://github.com/lobehub/lobe-chat",
  "form_fields": [
    {
      "type": "text",
      "label": "OpenAI API Key",
      "required": true,
      "env_variable": "OPENAI_API_KEY"
    },
    {
      "type": "url",
      "label": "OpenAI API URL",
      "required": false,
      "env_variable": "OPENAI_PROXY_URL"
    },
    {
      "type": "text",
      "label": "Custom Models",
      "hint": "Comma separated list of model IDs",
      "required": false,
      "env_variable": "CUSTOM_MODELS"
    },
    {
      "type": "password",
      "label": "Password",
      "required": false,
      "env_variable": "ACCESS_CODE"
    }
  ],
  "supported_architectures": ["arm64", "amd64"]
}

=== runtipi/runtipi-appstore/apps/homer/config.json
{
  "$schema": "../schema.json",
  "name": "Homer",
  "id": "homer",
  "available": true,
  "short_desc": "A very simple static homepage for your server",
  "author": "bastienwirtz",
  "port": 8562,
  "categories": ["utilities"],
  "description": "A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.",
  "tipi_version": 3,
  "version": "24.10.2",
  "source": "https://github.com/bastienwirtz/homer",
  "exposable": true,
  "supported_architectures": ["arm64", "amd64"],
  "dynamic_config": true,
  "form_fields": [],
  "created_at": 1729171012912,
  "updated_at": 1729978911000
}

=== runtipi/runtipi-appstore/apps/deemix/config.json
{
    "$schema": "../schema.json",
    "name": "Deemix",
    "port": 6595,
    "available": true,
    "exposable": true,
    "dynamic_config": true,
    "id": "deemix",
    "tipi_version": 3,
    "version": "latest",
    "categories": [ "media", "music" ],
    "description": "deemix is a barebone deezer downloader library built from the ashes of Deezloader Remix.",
    "short_desc": "deemix is a barebone deezer downloader library built from the ashes of Deezloader Remix.",
    "author": "Bockiii",
    "source": "https://gitlab.com/Bockiii/deemix-docker",
    "website": "https://deemix.app/",
    "form_fields": [],
    "supported_architectures": [ "arm64", "amd64" ],
    "created_at": 1691943801422,
    "updated_at": 1729872631894
}
